### ISSUE TITLE
Exception on "npm outdated" command

### ISSUE THREAD

**Issue by tobiasfiechter** [AnWeber/atom-npm-outdated#2]
```
TypeError: Cannot read property 'check' of null
    at /Users/appledev/.atom/packages/npm-outdated/lib/init.js:106:64
    at /Users/appledev/.atom/packages/npm-outdated/node_modules/lodash/lodash.js:4938:15
    at baseForOwn (/Users/appledev/.atom/packages/npm-outdated/node_modules/lodash/lodash.js:2988:24)
    at /Users/appledev/.atom/packages/npm-outdated/node_modules/lodash/lodash.js:4907:18
    at Function.forEach (/Users/appledev/.atom/packages/npm-outdated/node_modules/lodash/lodash.js:9319:14)
    at NpmOutdated.checkNpmHandlers (/Users/appledev/.atom/packages/npm-outdated/lib/init.js:106:12)
    at atom-workspace.<anonymous> (/Users/appledev/.atom/packages/npm-outdated/lib/init.js:49:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

**Comment by AnWeber** [comment]
I think your project is missing a package.json. In this case no NpmWatcher is created and the object is null.   After executing the comman 'npm-outdated' this exception is created. 
https://github.com/AnWeber/atom-npm-outdated/commit/883ea7154ea75817b3f86e16d0271e6d53a62125
I released a new version. thanks
